stages:
  - build
  - test

cache:
  paths:
    - frontend/osmmybiz/node_modules/

backend-test:
  image: python:3.6
  stage: test
  script:
    - cd backend/api
    - pip install -r requirements.txt
    - python test.py

client-build:
  image: node:8.4
  stage: build
  script:
    - cd frontend/osmmybiz
    - npm install
    - npm run build

client-unit:
  image: node:8.4
  stage: test
  script:
    - cd frontend/osmmybiz
    - npm install
    - npm run unit

client-lint:
  image: node:8.4
  stage: test
  script:
    - cd frontend/osmmybiz
    - npm install
    - npm run int