stages:
  - build
  - test
  - deploy

cache:
  paths:
    - frontend/osmybiz/node_modules/

backend-test:
  image: python:3.6
  stage: test
  script:
    - cd backend/api
    - pip install -r requirements.txt
    - python test.py

client-build:
  image: node:8.4
  stage: build
  script:
    - cd frontend/osmybiz
    - npm install
    - npm run build

client-unit:
  image: node:8.4
  stage: test
  script:
    - cd frontend/osmybiz
    - npm install
    - npm run unit

client-lint:
  image: node:8.4
  stage: test
  script:
    - cd frontend/osmybiz
    - npm install
    - npm run lint

pages:
  image: node:8.4
  stage: deploy
  script:
    - cd frontend/osmybiz
    - npm install
    - npm run build
    - cd ./../../
    - mkdir public
    - mv frontend/osmybiz/dist/* public
    - mkdir -p public/.well-known/acme-challenge/eTmh0ZhzO-NhDxx7vIqSyEGIDCwFgu_ZsQGXyr3kMSw
    - echo 'eTmh0ZhzO-NhDxx7vIqSyEGIDCwFgu_ZsQGXyr3kMSw.1AmwjUgTmx4IiwBW5EfhQyyoJBYyWdgBa-KEl5mm56E' > public/.well-known/acme-challenge/eTmh0ZhzO-NhDxx7vIqSyEGIDCwFgu_ZsQGXyr3kMSw
  artifacts:
    paths:
      - public
  only:
    - master
