version: '3.3'
services:
  app:
    build:
      context: backend/
      dockerfile: Dockerfile
    volumes:
      -  ./backend/api:/opt/api
    links:
      - database:database
  database:
    image: postgres
    environment:
      - POSTGRES_USER=osm-my-biz
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=osm-my-biz
