version: '3.3'
services:
  api: &api
    image: geometalab/osmmybiz-backend
    build:
      context: backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/api:/opt/backend
    links:
      - database:database
  api-migrate:
    <<: *api
    command: ["python", "manage.py", "db", "upgrade"]
  database:
    image: postgres
    environment:
      - POSTGRES_USER=osmybiz
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=osmybiz
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/osmybiz/src:/opt/frontend/src
      - ./frontend/osmybiz/static:/opt/frontend/static
      - ./frontend/osmybiz/index.html:/opt/frontend/index.html
      - ./frontend/osmybiz/package.json:/opt/frontend/package.json
      - ./frontend/osmybiz/package-lock.json:/opt/frontend/package-lock.json
  frontend-build:
    image: geometalab/osmmybiz-frontend
    build:
      context: frontend/
      dockerfile: Dockerfile.nginx
    command: []
  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VIRTUAL_HOST=localhost,127.0.0.1
    links:
      - "api:backend"
      - "frontend:frontend"
