FROM nginx:alpine

COPY ./nginx.conf-local.template /etc/nginx/conf.d/default.conf.template
COPY ./certs /etc/nginx/certs

CMD DOMAIN_NAMES=$(echo $VIRTUAL_HOST | sed 's/,/ /g') envsubst '$DOMAIN_NAMES' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf \
    && nginx -g 'daemon off;'
