"""empty message

Revision ID: 5b39e615ff01
Revises: 7185177c9e2c
Create Date: 2017-12-20 10:44:09.911183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b39e615ff01'
down_revision = '7185177c9e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('osm_id', sa.BigInteger(), nullable=True))
    op.add_column('node', sa.Column('receive_updates', sa.Boolean(), nullable=True))
    op.add_column('node', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('node_userId_fkey', 'node', type_='foreignkey')
    op.create_foreign_key(None, 'node', 'user', ['user_id'], ['id'])
    op.drop_column('node', 'osmId')
    op.drop_column('node', 'userId')
    op.drop_column('node', 'recieveUpdates')
    op.add_column('user', sa.Column('osm_id', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('osm_name', sa.String(), nullable=True))
    op.drop_column('user', 'osmId')
    op.drop_column('user', 'osmName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('osmName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('osmId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('user', 'osm_name')
    op.drop_column('user', 'osm_id')
    op.add_column('node', sa.Column('recieveUpdates', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('node', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('node', sa.Column('osmId', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'node', type_='foreignkey')
    op.create_foreign_key('node_userId_fkey', 'node', 'user', ['userId'], ['id'])
    op.drop_column('node', 'user_id')
    op.drop_column('node', 'receive_updates')
    op.drop_column('node', 'osm_id')
    # ### end Alembic commands ###
