"""empty message

Revision ID: b663e3538860
Revises: f6352d7f3bf5
Create Date: 2017-12-07 07:04:53.606400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b663e3538860'
down_revision = 'f6352d7f3bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'name')
    # ### end Alembic commands ###
