"""empty message

Revision ID: df8b0d746557
Revises: 21ed58aa3524
Create Date: 2018-11-06 14:08:37.197401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df8b0d746557'
down_revision = '21ed58aa3524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('note_without_node_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'note_without_node_id')
    # ### end Alembic commands ###
